#urls:
#  - "http://localhost*" #this will match URLs on localhost, this is the dev/testing default
#  - "http://www.lnwdr.de*"

server:
  port: 8000
  instance_name: null
  timeout: 20000
  send_timeout: 2000 #time that sending the repsonse data may take.
  access_log_format: "combined"
  base_url_path: "/"
  enable_load_test: false

test_server:
  enabled: false

cache:
  base_path: "cache"
  copy_source_file: true

download:
  url_whitelist:
    - "http://localhost/*"
  timeout: 5000
  rejectInvalidSSL: true

process:
  limit: 5
  timeout: 5000

analysis:
  aoi_name: "AOI"

converter:
  filter: false
  padding_color: "#fefe00"
  quality: false

cropping:
  default_mode: "aoi_coverage"
  prefer_embedded_aoi: false

constraints:
  quality:
    min: 1
    max: 100
    type: integer
  colors:
    min: 1
    max: 256
    type: integer
  width:
    min: 1
    max: 10000
    type: integer
  height:
    min: 1
    max: 10000
    type: integer
  blur:
    min: 0
    max: 100
    type: float

logging:
  error: "stderr"
  debug: "stderr"
  access: "stdout"
  info: "stdout"

source_url_header: false

garbage_collector:
  enabled: false
  source: "cache"
  target: "immediate"
  interval: 10000
